issuer: https://token.actions.githubusercontent.com
subject: repo:test-fabz-organization/test-octo-sts:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: test-fabz-organization/test-octo-sts/.github/workflows/update-readme.yml@.*

permissions:
  contents: write